name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Trigger deployment on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debug File Upload
      run: |
        RESPONSE=$(curl -s -w "%{http_code}" --upload-file bot.py \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/path/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bot.py)
        
        echo "Bot.py Upload Response: $RESPONSE"

        RESPONSE=$(curl -s -w "%{http_code}" --upload-file requirements.txt \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/path/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/requirements.txt)

        echo "Requirements.txt Upload Response: $RESPONSE"

    - name: Verify File Upload
      run: |
        curl -X GET \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/tree/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/

    - name: Upload Environment Variables
      run: |
        echo -e "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}\nCHAT_ID=${{ secrets.CHAT_ID }}\nURL=${{ secrets.URL }}\nCHECK_INTERVAL=${{ secrets.CHECK_INTERVAL }}" > .env
        curl --upload-file .env \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/path/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/.env

    - name: Run Bot on PythonAnywhere
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/ \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        -d '{"executable": "/bin/bash"}'
        
        sleep 5
        
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/ \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        -d '{"command": "pip install --upgrade python-telegram-bot && python bot.py & disown"}'
    
env:
      PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
