name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Trigger deployment on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to PythonAnywhere using API
      run: |
        curl -X PUT --data-binary @bot.py \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/bot.py
        
        curl -X PUT --data-binary @requirements.txt \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/requirements.txt

    - name: Install Dependencies on PythonAnywhere
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/ \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        -d '{"executable": "/bin/bash"}'

    - name: Upload Environment Variables
      run: |
        curl -X PUT --data-binary @<(echo -e "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}\nCHAT_ID=${{ secrets.CHAT_ID }}\nURL=${{ secrets.URL }}\nCHECK_INTERVAL=${{ secrets.CHECK_INTERVAL }}") \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/files/home/${{ secrets.PYTHONANYWHERE_USERNAME }}/.env

    - name: Run Bot on PythonAnywhere
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/ \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        -d '{"executable": "/bin/bash"}'
        
        sleep 5
        
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/ \
        -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
        -d '{"command": "pip install python-telegram-bot --upgrade && python bot.py"}'
    
env:
      PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
