name: Redeploy Bot

on:
  workflow_dispatch:
    inputs:
      wait_time:
        description: 'Seconds to wait before restarting'
        required: true
        default: '300'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for specified time
      run: sleep ${{ github.event.inputs.wait_time }}

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Trigger Railway Deployment
      run: |
        curl -X POST "https://backboard.railway.app/graphql/v2" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
        --data '{"query":"mutation { deploymentCreate(input: { serviceId: \"${{ secrets.RAILWAY_SERVICE_ID }}\" }) { id } }"}'
