name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Triggers deployment on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "$PA_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

    - name: Upload Bot Files to PythonAnywhere
      run: |
        scp bot.py requirements.txt 1Godfather@ssh.pythonanywhere.com:/home/1Godfather/

    - name: Install Dependencies on PythonAnywhere
      run: |
        ssh 1Godfather@ssh.pythonanywhere.com << 'EOF'
          pip install --upgrade python-telegram-bot python-dotenv
        EOF

    - name: Restart PythonAnywhere Bot
      run: |
        ssh 1Godfather@ssh.pythonanywhere.com << 'EOF'
          pkill -f bot.py || true  # Stop any running bot instance
          nohup python3 /home/1Godfather/bot.py > bot.log 2>&1 &
        EOF
    
    - name: Upload Environment Variables
  run: |
    ssh 1Godfather@ssh.pythonanywhere.com << 'EOF'
    echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > /home/1Godfather/.env
    echo "URL=${{ secrets.URL }}" >> /home/1Godfather/.env
    EOF

    env:
      PA_SSH_PRIVATE_KEY: ${{ secrets.PA_SSH_PRIVATE_KEY }}
