name: Deploy to Replit

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Configure Git for Replit
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone Replit Repository
      run: |
        git clone "https://replit.com/@${{ secrets.REPLIT_USERNAME }}/${{ secrets.REPLIT_PROJECT }}.git" replit-project
        cd replit-project
        git checkout main

    - name: Push Latest Code to Replit
      run: |
        cd replit-project
        git remote set-url origin "https://replit.com/@${{ secrets.REPLIT_USERNAME }}/${{ secrets.REPLIT_PROJECT }}.git"
        git add .
        git commit -m "Automated GitHub Actions Deployment" || echo "No changes to commit"
        git push origin main --force

    - name: Restart Bot on Replit
      run: |
        curl -X POST https://replit.com/@${{ secrets.REPLIT_USERNAME }}/${{ secrets.REPLIT_PROJECT }}/restart
