name: Universal Deploy Bot

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to deploy (railway, replit, fly, heroku, render)'
        required: true
        default: 'railway'
      wait_time:
        description: 'Seconds to wait before restarting'
        required: true
        default: '300'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait before redeploying
      if: github.event.inputs.platform == 'railway' || github.event.inputs.platform == 'heroku'
      run: |
        echo "Waiting for ${{ github.event.inputs.wait_time }} seconds before redeploying..."
        sleep ${{ github.event.inputs.wait_time }}

    - name: Deploy to Railway
      if: github.event.inputs.platform == 'railway'
      env:
        RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
        RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      run: |
        curl -X POST "https://backboard.railway.app/graphql/v2" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $RAILWAY_API_KEY" \
        --data '{"query":"mutation { deploymentCreate(input: { serviceId: \"$RAILWAY_SERVICE_ID\" }) { id } }"}'

    - name: Deploy to Replit
      if: github.event.inputs.platform == 'replit'
      run: |
        curl -X POST "https://replit.com/api/v1/deploy" \
        -H "Authorization: Bearer ${{ secrets.REPLIT_API_KEY }}" \
        -d '{"project_id": "${{ secrets.REPLIT_PROJECT_ID }}"}'

    - name: Deploy to Fly.io
      if: github.event.inputs.platform == 'fly'
      run: |
        flyctl deploy --app ${{ secrets.FLY_APP_ID }} --remote-only

    - name: Deploy to Heroku
      if: github.event.inputs.platform == 'heroku'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        heroku container:release web --app $HEROKU_APP_NAME

    - name: Deploy to Render
      if: github.event.inputs.platform == 'render'
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
