- name: Deploy to PythonAnywhere
  env:
    PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
    PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
  run: |
    echo "Uploading files to PythonAnywhere..."
    curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
      https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/files/path/home/$PA_USERNAME/bot.py \
      --upload-file bot.py

    echo "Restarting PythonAnywhere web app..."
    curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
      https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/YOUR_WEB_APP_DOMAIN/reload/
